const fs = require("fs");
const path = require("path");

const manifestPath = process.argv[2];
const outDir = process.argv[3] || ".";

const PREFIXES = ["fill-", "pad-", "gap-", "radius-", "text-", "comp-"];

const variables = JSON.parse(fs.readFileSync(manifestPath, "utf8")).menu.filter(
  (m) => m.command && PREFIXES.some((p) => m.command.startsWith(p))
);

const DELIM = "BIFROST_VAR_LIST_EOF";
const NBSP = String.fromCharCode(0xa0);
const names = variables.map((v) => v.name).join("\n");

const undoScript = `#!/bin/bash
# Removes ONLY the rows in the list below that are NOT commented out with #.
# Put # in front of a line to skip it.
# Covers the Fill/Padding/Gap/Radius/Text/Component menu items generated by generate.js.

BUNDLE_ID="com.figma.Desktop"
PLIST="$HOME/Library/Preferences/\${BUNDLE_ID}.plist"

BACKUP="$HOME/figma-shortcuts-backup-$(date +%s)-$$.plist"
defaults export "$BUNDLE_ID" "$BACKUP"
echo "Backup saved: $BACKUP"

osascript -e 'quit app "Figma"' 2>/dev/null || true
sleep 1
killall cfprefsd 2>/dev/null || true

count=0
skipped=0
fail=0
while IFS= read -r name; do
  [ -z "$name" ] && continue
  case "$name" in
    "#"*) skipped=$((skipped+1)); continue;;
  esac
  if /usr/libexec/PlistBuddy -c "Delete :NSUserKeyEquivalents:\\"$name\\"" "$PLIST" 2>/dev/null; then
    count=$((count+1))
  else
    fail=$((fail+1))
  fi
done << '${DELIM}'
${names}
${DELIM}

killall cfprefsd 2>/dev/null || true
echo "Removed: $count. Commented out/skipped: $skipped. Not found: $fail."
echo "Restart Figma so System Settings shows the correct state."
`;

const setupScript = `#!/bin/bash
# Adds placeholder rows for every line below that does NOT start with #.
# Put # in front of a line to leave that item out of System Settings.
# Covers the Fill/Padding/Gap/Radius/Text/Component menu items generated by generate.js.
#
# IDEMPOTENT: uses PlistBuddy "Add" instead of "defaults write -dict-add".
# Add fails (on purpose) if the key already exists, so a shortcut you've
# already set for one of these rows is NEVER overwritten or reset.
# Only rows that are missing entirely get a new, empty placeholder.

BUNDLE_ID="com.figma.Desktop"  # verify: osascript -e 'id of app "Figma"'
PLIST="$HOME/Library/Preferences/\${BUNDLE_ID}.plist"

BACKUP="$HOME/figma-shortcuts-backup-$(date +%s)-$$.plist"
defaults export "$BUNDLE_ID" "$BACKUP"
echo "Backup saved: $BACKUP"

osascript -e 'quit app "Figma"' 2>/dev/null || true
sleep 1
killall cfprefsd 2>/dev/null || true

# Make sure the NSUserKeyEquivalents dictionary itself exists (no-op if it does)
/usr/libexec/PlistBuddy -c "Add :NSUserKeyEquivalents dict" "$PLIST" 2>/dev/null || true

added=0
kept=0
skipped=0
while IFS= read -r name; do
  [ -z "$name" ] && continue
  case "$name" in
    "#"*) skipped=$((skipped+1)); continue;;
  esac
  if /usr/libexec/PlistBuddy -c "Add :NSUserKeyEquivalents:\\"$name\\" string ${NBSP}" "$PLIST" 2>/dev/null; then
    added=$((added+1))
  else
    kept=$((kept+1))
  fi
done << '${DELIM}'
${names}
${DELIM}

killall cfprefsd 2>/dev/null || true
echo "New placeholders added: $added. Kept untouched (already existed): $kept. Commented out: $skipped."
echo "Fully restart Figma for System Settings to show them."
`;

fs.writeFileSync(path.join(outDir, "undo-shortcuts.sh"), undoScript);
fs.writeFileSync(path.join(outDir, "setup-shortcut-placeholders.sh"), setupScript);
console.log(`Wrote both scripts with ${variables.length} menu items (fill+padding+gap+radius+text+component).`);