#!/bin/bash
# Removes ONLY the rows in the list below that are NOT commented out with #.
# Put # in front of a line to skip it.
# Covers the Fill/Padding/Gap/Radius/Text/Component menu items generated by generate.js.

BUNDLE_ID="com.figma.Desktop"
PLIST="$HOME/Library/Preferences/${BUNDLE_ID}.plist"

BACKUP="$HOME/figma-shortcuts-backup-$(date +%s)-$$.plist"
defaults export "$BUNDLE_ID" "$BACKUP"
echo "Backup saved: $BACKUP"

osascript -e 'quit app "Figma"' 2>/dev/null || true
sleep 1
killall cfprefsd 2>/dev/null || true

count=0
skipped=0
fail=0
while IFS= read -r name; do
  [ -z "$name" ] && continue
  case "$name" in
    "#"*) skipped=$((skipped+1)); continue;;
  esac
  if /usr/libexec/PlistBuddy -c "Delete :NSUserKeyEquivalents:\"$name\"" "$PLIST" 2>/dev/null; then
    count=$((count+1))
  else
    fail=$((fail+1))
  fi
done << 'BIFROST_VAR_LIST_EOF'
Fill - Base/bfc-base-1
Fill - Base/bfc-base-2
Fill - Base/bfc-base-3
Fill - Base/bfc-base-dimmed
Fill - Base/bfc-base-dimmed-2
Fill - Base/bfc-base-dimmed-3
Fill - Base/bfc-base-disabled
Fill - Base/bfc-base-c-1
Fill - Base/bfc-base-c-2
Fill - Base/bfc-base-c-theme
Fill - Base/bfc-base-c-brand
Fill - Base/bfc-base-c-chill
Fill - Base/bfc-base-c-attn
Fill - Base/bfc-base-c-success
Fill - Base/bfc-base-c-warning
Fill - Base/bfc-base-c-alert
Fill - Base/bfc-base-c-wcag
Fill - Base/bfc-base-c-dimmed
Fill - Base/bfc-base-c-disabled
Fill - Base/bfc-base-c-inverted-1
Fill - Base/bfc-base-c-inverted-2
Fill - Base/bfc-base-c-inverted-3
Fill - Theme/bfc-theme-1
Fill - Theme/bfc-theme-2
Fill - Theme/bfc-theme-3
Fill - Theme/bfc-theme-c-1
Fill - Theme/bfc-theme-c-2
Fill - Theme/bfc-theme-hc
Fill - Theme/bfc-theme-fade
Fill - Theme/bfc-theme-fade-c
Fill - Pop/Neutral/bfc-neutral
Fill - Pop/Neutral/bfc-neutral-2
Fill - Pop/Neutral/bfc-neutral-c
Fill - Pop/Neutral/bfc-neutral-hc
Fill - Pop/Neutral/bfc-neutral-fade
Fill - Pop/Neutral/bfc-neutral-fade-c
Fill - Pop/Brand/bfc-brand
Fill - Pop/Brand/bfc-brand-c
Fill - Pop/Brand/bfc-brand-hc
Fill - Pop/Brand/bfc-brand-fade
Fill - Pop/Brand/bfc-brand-fade-c
Fill - Pop/Chill/bfc-chill
Fill - Pop/Chill/bfc-chill-c
Fill - Pop/Chill/bfc-chill-hc
Fill - Pop/Chill/bfc-chill-fade
Fill - Pop/Chill/bfc-chill-fade-c
Fill - Pop/Attention/bfc-attn
Fill - Pop/Success/bfc-success
Fill - Pop/Success/bfc-success-c
Fill - Pop/Success/bfc-success-hc
Fill - Pop/Success/bfc-success-fade
Fill - Pop/Success/bfc-success-fade-c
Fill - Pop/Attention/bfc-attn-c
Fill - Pop/Attention/bfc-attn-hc
Fill - Pop/Attention/bfc-attn-fade
Fill - Pop/Attention/bfc-attn-fade-c
Fill - Pop/Warning/bfc-warning
Fill - Pop/Warning/bfc-warning-c
Fill - Pop/Warning/bfc-warning-hc
Fill - Pop/Warning/bfc-warning-fade
Fill - Pop/Warning/bfc-warning-fade-c
Fill - Pop/Alert/bfc-alert
Fill - Pop/Alert/bfc-alert-2
Fill - Pop/Alert/bfc-alert-c
Fill - Pop/Alert/bfc-alert-hc
Fill - Pop/Alert/bfc-alert-fade
Fill - Pop/Alert/bfc-alert-fade-c
Fill - Pop/Alert/bfc-alert-fade-2
Fill - Pop/Alert/bfc-alert-fade-2-c
Fill - Miscellaneous/bfc-overlay
Fill - Miscellaneous/bfc-overlay-c
Fill - Miscellaneous/ios-browser-bg
Fill - Miscellaneous/transparent-base-3
Fill - Miscellaneous/transparent-base-2
Fill - Miscellaneous/transparent-base-1
Fill - Miscellaneous/transparent-base-dimmed
Fill - Miscellaneous/high-contrast
Fill - Miscellaneous/high-contrast-inv
Fill - Effect variables/Shadows/Opacity/bfc-theme-1-40
Fill - Effect variables/Shadows/Opacity/bfc-shadow
Fill - Effect variables/Shadows/Opacity/200
Fill - Effect variables/Shadows/Opacity/300
Fill - Effect variables/Shadows/Opacity/400
Fill - Teal/0
Fill - Teal/10
Fill - Teal/20
Fill - Teal/30
Fill - Teal/40
Fill - Teal/50
Fill - Teal/60
Fill - Teal/70
Fill - Teal/80
Fill - Teal/90
Fill - Teal/100
Fill - Teal/110
Fill - Teal/120
Fill - Teal/130
Fill - Teal/140
Fill - Teal/150
Fill - Teal/160
Fill - Teal/170
Fill - Teal/180
Fill - Teal/190
Fill - Teal/200
Fill - Teal/210
Fill - Teal/220
Fill - Teal/230
Fill - Teal/240
Fill - Teal/250
Fill - Teal/260
Fill - Teal/270
Fill - Teal/280
Fill - Teal/290
Fill - Teal/300
Fill - Teal/310
Fill - Teal/320
Fill - Teal/330
Fill - Teal/340
Fill - Teal/350
Fill - Teal/360
Fill - Teal/370
Fill - Teal/380
Fill - Teal/390
Fill - Teal/400
Fill - Teal/410
Fill - Teal/420
Fill - Teal/430
Fill - Teal/440
Fill - Teal/450
Fill - Teal/460
Fill - Teal/470
Fill - Teal/480
Fill - Teal/490
Fill - Teal/500
Fill - Teal/510
Fill - Teal/520
Fill - Teal/530
Fill - Teal/540
Fill - Teal/550
Fill - Teal/560
Fill - Teal/570
Fill - Teal/580
Fill - Teal/590
Fill - Teal/600
Fill - Teal/610
Fill - Teal/620
Fill - Teal/630
Fill - Teal/640
Fill - Teal/650
Fill - Teal/660
Fill - Teal/670
Fill - Teal/680
Fill - Teal/690
Fill - Teal/700
Fill - Teal/710
Fill - Teal/720
Fill - Teal/730
Fill - Teal/740
Fill - Teal/750
Fill - Teal/760
Fill - Teal/770
Fill - Teal/780
Fill - Teal/790
Fill - Teal/800
Fill - Teal/810
Fill - Teal/820
Fill - Teal/830
Fill - Teal/840
Fill - Teal/850
Fill - Teal/860
Fill - Teal/870
Fill - Teal/880
Fill - Teal/890
Fill - Teal/900
Fill - Teal/910
Fill - Teal/920
Fill - Teal/930
Fill - Teal/940
Fill - Teal/950
Fill - Teal/960
Fill - Teal/970
Fill - Teal/980
Fill - Teal/990
Fill - Teal/1000
Fill - Purple/0
Fill - Pink/0
Fill - Pink/10
Fill - Pink/20
Fill - Pink/30
Fill - Pink/40
Fill - Pink/50
Fill - Pink/60
Fill - Pink/70
Fill - Pink/80
Fill - Pink/90
Fill - Pink/100
Fill - Pink/110
Fill - Pink/120
Fill - Pink/130
Fill - Pink/140
Fill - Pink/150
Fill - Pink/160
Fill - Pink/170
Fill - Pink/180
Fill - Pink/190
Fill - Pink/200
Fill - Pink/210
Fill - Pink/220
Fill - Pink/230
Fill - Pink/240
Fill - Pink/250
Fill - Pink/260
Fill - Pink/270
Fill - Pink/280
Fill - Pink/290
Fill - Pink/300
Fill - Pink/310
Fill - Pink/320
Fill - Pink/330
Fill - Pink/340
Fill - Pink/350
Fill - Pink/360
Fill - Pink/370
Fill - Pink/380
Fill - Pink/390
Fill - Pink/400
Fill - Pink/410
Fill - Pink/420
Fill - Pink/430
Fill - Pink/440
Fill - Pink/450
Fill - Pink/460
Fill - Pink/470
Fill - Pink/480
Fill - Pink/490
Fill - Pink/500
Fill - Pink/510
Fill - Pink/520
Fill - Pink/530
Fill - Pink/540
Fill - Pink/550
Fill - Pink/560
Fill - Pink/570
Fill - Pink/580
Fill - Pink/590
Fill - Pink/600
Fill - Pink/610
Fill - Pink/620
Fill - Pink/630
Fill - Pink/640
Fill - Pink/650
Fill - Pink/660
Fill - Pink/670
Fill - Pink/680
Fill - Pink/690
Fill - Pink/700
Fill - Pink/710
Fill - Pink/720
Fill - Pink/730
Fill - Pink/740
Fill - Pink/750
Fill - Pink/760
Fill - Pink/770
Fill - Pink/780
Fill - Pink/790
Fill - Pink/800
Fill - Pink/810
Fill - Pink/820
Fill - Pink/830
Fill - Pink/840
Fill - Pink/850
Fill - Pink/860
Fill - Pink/870
Fill - Pink/880
Fill - Pink/890
Fill - Pink/900
Fill - Pink/910
Fill - Pink/920
Fill - Pink/930
Fill - Pink/940
Fill - Pink/950
Fill - Pink/960
Fill - Pink/970
Fill - Pink/980
Fill - Pink/990
Fill - Pink/1000
Fill - Purple/10
Fill - Purple/20
Fill - Purple/30
Fill - Purple/40
Fill - Purple/50
Fill - Purple/60
Fill - Purple/70
Fill - Purple/80
Fill - Purple/90
Fill - Purple/100
Fill - Purple/110
Fill - Purple/120
Fill - Purple/130
Fill - Purple/140
Fill - Purple/150
Fill - Purple/160
Fill - Purple/170
Fill - Purple/180
Fill - Purple/190
Fill - Purple/200
Fill - Purple/210
Fill - Purple/220
Fill - Purple/230
Fill - Purple/240
Fill - Purple/250
Fill - Purple/260
Fill - Purple/270
Fill - Purple/280
Fill - Purple/290
Fill - Purple/300
Fill - Purple/310
Fill - Purple/320
Fill - Purple/330
Fill - Purple/340
Fill - Purple/350
Fill - Purple/360
Fill - Purple/370
Fill - Purple/380
Fill - Purple/390
Fill - Purple/400
Fill - Purple/410
Fill - Purple/420
Fill - Purple/430
Fill - Purple/440
Fill - Purple/450
Fill - Purple/460
Fill - Purple/470
Fill - Purple/480
Fill - Purple/490
Fill - Purple/500
Fill - Purple/510
Fill - Purple/520
Fill - Purple/530
Fill - Purple/540
Fill - Purple/550
Fill - Purple/560
Fill - Purple/570
Fill - Purple/580
Fill - Purple/590
Fill - Purple/600
Fill - Purple/610
Fill - Purple/620
Fill - Purple/630
Fill - Purple/640
Fill - Purple/650
Fill - Purple/660
Fill - Purple/670
Fill - Purple/680
Fill - Purple/690
Fill - Purple/700
Fill - Purple/710
Fill - Purple/720
Fill - Purple/730
Fill - Purple/740
Fill - Purple/750
Fill - Purple/760
Fill - Purple/770
Fill - Purple/780
Fill - Purple/790
Fill - Purple/800
Fill - Purple/810
Fill - Purple/820
Fill - Purple/830
Fill - Purple/840
Fill - Purple/850
Fill - Purple/860
Fill - Purple/870
Fill - Purple/880
Fill - Purple/890
Fill - Purple/900
Fill - Purple/910
Fill - Purple/920
Fill - Purple/930
Fill - Purple/940
Fill - Purple/950
Fill - Purple/960
Fill - Purple/970
Fill - Purple/980
Fill - Purple/990
Fill - Purple/1000
Fill - Green/0
Fill - Green/10
Fill - Green/20
Fill - Green/30
Fill - Green/40
Fill - Green/50
Fill - Green/60
Fill - Green/70
Fill - Green/80
Fill - Green/90
Fill - Green/100
Fill - Green/110
Fill - Green/120
Fill - Green/130
Fill - Green/140
Fill - Green/150
Fill - Green/160
Fill - Green/170
Fill - Green/180
Fill - Green/190
Fill - Green/200
Fill - Green/210
Fill - Green/220
Fill - Green/230
Fill - Green/240
Fill - Green/250
Fill - Green/260
Fill - Green/270
Fill - Green/280
Fill - Green/290
Fill - Green/300
Fill - Green/310
Fill - Green/320
Fill - Green/330
Fill - Green/340
Fill - Green/350
Fill - Green/360
Fill - Green/370
Fill - Green/380
Fill - Green/390
Fill - Green/400
Fill - Green/410
Fill - Green/420
Fill - Green/430
Fill - Green/440
Fill - Green/450
Fill - Green/460
Fill - Green/470
Fill - Green/480
Fill - Green/490
Fill - Green/500
Fill - Green/510
Fill - Green/520
Fill - Green/530
Fill - Green/540
Fill - Green/550
Fill - Green/560
Fill - Green/570
Fill - Green/580
Fill - Green/590
Fill - Green/600
Fill - Green/610
Fill - Green/620
Fill - Green/630
Fill - Green/640
Fill - Green/650
Fill - Green/660
Fill - Green/670
Fill - Green/680
Fill - Green/690
Fill - Green/700
Fill - Green/710
Fill - Green/720
Fill - Green/730
Fill - Green/740
Fill - Green/750
Fill - Green/760
Fill - Green/770
Fill - Green/780
Fill - Green/790
Fill - Green/800
Fill - Green/810
Fill - Green/820
Fill - Green/830
Fill - Green/840
Fill - Green/850
Fill - Green/860
Fill - Green/870
Fill - Green/880
Fill - Green/890
Fill - Green/900
Fill - Green/910
Fill - Green/920
Fill - Green/930
Fill - Green/940
Fill - Green/950
Fill - Green/960
Fill - Green/970
Fill - Green/980
Fill - Green/990
Fill - Green/1000
Fill - Yellow/0
Fill - Yellow/10
Fill - Yellow/20
Fill - Yellow/30
Fill - Yellow/40
Fill - Yellow/50
Fill - Yellow/60
Fill - Yellow/70
Fill - Yellow/80
Fill - Yellow/90
Fill - Yellow/100
Fill - Yellow/110
Fill - Yellow/120
Fill - Yellow/130
Fill - Yellow/140
Fill - Yellow/150
Fill - Yellow/160
Fill - Yellow/170
Fill - Yellow/180
Fill - Yellow/190
Fill - Yellow/200
Fill - Yellow/210
Fill - Yellow/220
Fill - Yellow/230
Fill - Yellow/240
Fill - Yellow/250
Fill - Yellow/260
Fill - Yellow/270
Fill - Yellow/280
Fill - Yellow/290
Fill - Yellow/300
Fill - Yellow/310
Fill - Yellow/320
Fill - Yellow/330
Fill - Yellow/340
Fill - Yellow/350
Fill - Yellow/360
Fill - Yellow/370
Fill - Yellow/380
Fill - Yellow/390
Fill - Yellow/400
Fill - Yellow/410
Fill - Yellow/420
Fill - Yellow/430
Fill - Yellow/440
Fill - Yellow/450
Fill - Yellow/460
Fill - Yellow/470
Fill - Yellow/480
Fill - Yellow/490
Fill - Yellow/500
Fill - Yellow/510
Fill - Yellow/520
Fill - Yellow/530
Fill - Yellow/540
Fill - Yellow/550
Fill - Yellow/560
Fill - Yellow/570
Fill - Yellow/580
Fill - Yellow/590
Fill - Yellow/600
Fill - Yellow/610
Fill - Yellow/620
Fill - Yellow/630
Fill - Yellow/640
Fill - Yellow/650
Fill - Yellow/660
Fill - Yellow/670
Fill - Yellow/680
Fill - Yellow/690
Fill - Yellow/700
Fill - Yellow/710
Fill - Yellow/720
Fill - Yellow/730
Fill - Yellow/740
Fill - Yellow/750
Fill - Yellow/760
Fill - Yellow/770
Fill - Yellow/780
Fill - Yellow/790
Fill - Yellow/800
Fill - Yellow/810
Fill - Yellow/820
Fill - Yellow/830
Fill - Yellow/840
Fill - Yellow/850
Fill - Yellow/860
Fill - Yellow/870
Fill - Yellow/880
Fill - Yellow/890
Fill - Yellow/900
Fill - Yellow/910
Fill - Yellow/920
Fill - Yellow/930
Fill - Yellow/940
Fill - Yellow/950
Fill - Yellow/960
Fill - Yellow/970
Fill - Yellow/980
Fill - Yellow/990
Fill - Yellow/1000
Fill - Red/0
Fill - Red/10
Fill - Red/20
Fill - Red/30
Fill - Red/40
Fill - Red/50
Fill - Red/60
Fill - Red/70
Fill - Red/80
Fill - Red/90
Fill - Red/100
Fill - Red/110
Fill - Red/120
Fill - Red/130
Fill - Red/140
Fill - Red/150
Fill - Red/160
Fill - Red/170
Fill - Red/180
Fill - Red/190
Fill - Red/200
Fill - Red/210
Fill - Red/220
Fill - Red/230
Fill - Red/240
Fill - Red/250
Fill - Red/260
Fill - Red/270
Fill - Red/280
Fill - Red/290
Fill - Red/300
Fill - Red/310
Fill - Red/320
Fill - Red/330
Fill - Red/340
Fill - Red/350
Fill - Red/360
Fill - Red/370
Fill - Red/380
Fill - Red/390
Fill - Red/400
Fill - Red/410
Fill - Red/420
Fill - Red/430
Fill - Red/440
Fill - Red/450
Fill - Red/460
Fill - Red/470
Fill - Red/480
Fill - Red/490
Fill - Red/500
Fill - Red/510
Fill - Red/520
Fill - Red/530
Fill - Red/540
Fill - Red/550
Fill - Red/560
Fill - Red/570
Fill - Red/580
Fill - Red/590
Fill - Red/600
Fill - Red/610
Fill - Red/620
Fill - Red/630
Fill - Red/640
Fill - Red/650
Fill - Red/660
Fill - Red/670
Fill - Red/680
Fill - Red/690
Fill - Red/700
Fill - Red/710
Fill - Red/720
Fill - Red/730
Fill - Red/740
Fill - Red/750
Fill - Red/760
Fill - Red/770
Fill - Red/780
Fill - Red/790
Fill - Red/800
Fill - Red/810
Fill - Red/820
Fill - Red/830
Fill - Red/840
Fill - Red/850
Fill - Red/860
Fill - Red/870
Fill - Red/880
Fill - Red/890
Fill - Red/900
Fill - Red/910
Fill - Red/920
Fill - Red/930
Fill - Red/940
Fill - Red/950
Fill - Red/960
Fill - Red/970
Fill - Red/980
Fill - Red/990
Fill - Red/1000
Fill - Gray/50
Fill - Gray/100
Fill - Gray/150
Fill - Gray/800
Fill - Gray/920
Fill - Gray/970
Fill - Light/Theme/base-c-theme
Fill - Light/Theme/theme-1
Fill - Light/Theme/theme-2
Fill - Light/Theme/theme-3
Fill - Light/Theme/theme-c-1
Fill - Light/Theme/theme-c-2
Fill - Light/Theme/theme-hc
Fill - Light/Theme/Fade/theme-fade
Fill - Light/Theme/Fade/theme-fade-c
Fill - Dark/Theme/base-c-theme
Fill - Dark/Theme/theme-1
Fill - Dark/Theme/theme-2
Fill - Dark/Theme/theme-3
Fill - Dark/Theme/theme-c-1
Fill - Dark/Theme/theme-c-2
Fill - Dark/Theme/theme-hc
Fill - Dark/Theme/Fade/theme-fade
Fill - Dark/Theme/Fade/theme-fade-c
Fill - 0
Fill - 10
Fill - 20
Fill - 30
Fill - 40
Fill - 50
Fill - 60
Fill - 70
Fill - 80
Fill - 90
Fill - 100
Fill - 110
Fill - 120
Fill - 130
Fill - 140
Fill - 150
Fill - 160
Fill - 170
Fill - 180
Fill - 190
Fill - 200
Fill - 210
Fill - 220
Fill - 230
Fill - 240
Fill - 250
Fill - 260
Fill - 270
Fill - 280
Fill - 290
Fill - 300
Fill - 310
Fill - 320
Fill - 330
Fill - 340
Fill - 350
Fill - 360
Fill - 370
Fill - 380
Fill - 390
Fill - 400
Fill - 410
Fill - 420
Fill - 430
Fill - 440
Fill - 450
Fill - 460
Fill - 470
Fill - 480
Fill - 490
Fill - 500
Fill - 510
Fill - 520
Fill - 530
Fill - 540
Fill - 550
Fill - 560
Fill - 570
Fill - 580
Fill - 590
Fill - 600
Fill - 610
Fill - 620
Fill - 630
Fill - 640
Fill - 650
Fill - 660
Fill - 670
Fill - 680
Fill - 690
Fill - 700
Fill - 710
Fill - 720
Fill - 730
Fill - 740
Fill - 750
Fill - 760
Fill - 770
Fill - 780
Fill - 790
Fill - 800
Fill - 810
Fill - 820
Fill - 830
Fill - 840
Fill - 850
Fill - 860
Fill - 870
Fill - 880
Fill - 890
Fill - 900
Fill - 910
Fill - 920
Fill - 930
Fill - 940
Fill - 950
Fill - 960
Fill - 970
Fill - 980
Fill - 990
Fill - 1000
Padding - None
Padding - XXS
Padding - XS
Padding - S
Padding - M
Padding - L
Padding - XL
Padding - XXL
Padding - 3XL
Padding - 4XL
Padding - 5XL
Padding - 6XL
Gap - None
Gap - XXS
Gap - XS
Gap - S
Gap - M
Gap - L
Gap - XL
Gap - XXL
Gap - 3XL
Gap - 4XL
Gap - 5XL
Gap - 6XL
Radius - None
Radius - XS
Radius - S
Radius - M
Radius - L
Radius - XL
Radius - Full
Text - S/Open Sans/Regular/Text
Text - S/Open Sans/Regular/Link
Text - S/Open Sans/Semibold/Text
Text - S/Open Sans/Semibold/Link
Text - S/Open Sans/Italic/Text
Text - S/Open Sans/Italic/Link
Text - S/Open Sans/Semibold italic/Text
Text - S/Open Sans/Semibold italic/Link
Text - S/Font Awesome/Regular
Text - S/Font Awesome/Solid
Text - S/Font Awesome/Duotone
Text - S/Font Awesome/Brands
Text - M/Open Sans/Regular/Text
Text - M/Open Sans/Regular/Link
Text - M/Open Sans/Semibold/Text
Text - M/Open Sans/Semibold/Link
Text - M/Open Sans/Italic/Text
Text - M/Open Sans/Italic/Link
Text - M/Open Sans/Semibold italic/Text
Text - M/Open Sans/Semibold italic/Link
Text - M/Font Awesome/Regular
Text - M/Font Awesome/Solid
Text - M/Font Awesome/Duotone
Text - M/Font Awesome/Brands
Text - L/Open Sans/Regular/Text
Text - L/Open Sans/Regular/Link
Text - L/Open Sans/Semibold/Text
Text - L/Open Sans/Semibold/Link
Text - L/Open Sans/Italic/Text
Text - L/Open Sans/Italic/Link
Text - L/Open Sans/Semibold italic/Text
Text - L/Open Sans/Semibold italic/Link
Text - L/Font Awesome/Regular
Text - L/Font Awesome/Solid
Text - L/Font Awesome/Duotone
Text - L/Font Awesome/Brands
Text - H5
Text - H5/Satoshi/Link
Text - H5/Font Awesome/Regular
Text - H5/Font Awesome/Solid
Text - H5/Font Awesome/Duotone
Text - H5/Font Awesome/Brands
Text - H4
Text - H4/Satoshi/Link
Text - H4/Font Awesome/Regular
Text - H4/Font Awesome/Solid
Text - H4/Font Awesome/Duotone
Text - H4/Font Awesome/Brands
Text - H3
Text - H3/Satoshi/Link
Text - H3/Font Awesome/Regular
Text - H3/Font Awesome/Solid
Text - H3/Font Awesome/Duotone
Text - H3/Font Awesome/Brands
Text - H2
Text - H2/Satoshi/Link
Text - H2/Font Awesome/Light
Text - H2/Font Awesome/Regular
Text - H2/Font Awesome/Solid
Text - H2/Font Awesome/Duotone
Text - H2/Font Awesome/Brands
Text - H1
Text - H1/Satoshi/Link
Text - H1/Font Awesome/Light
Text - H1/Font Awesome/Regular
Text - H1/Font Awesome/Solid
Text - H1/Font Awesome/Duotone
Text - H1/Font Awesome/Brands
Component - Accordion-basic
Component - Accordion-styled
Component - Article-card-horizontal
Component - Article-card-vertical
Component - Backdrop
Component - Badge
Component - BottomBar
Component - Box
Component - Breadcrumbs
Component - Button.Group
Component - Button.Expand
Component - Button
Component - Button (icon only)
Component - Checkbox-button
Component - Checkbox-indeterminate-button
Component - Checkbox-indeterminate
Component - Checkbox
Component - CheckboxCard-basic
Component - CheckboxCard-indeterminate
Component - DatePicker (with input)
Component - DatePicker (with presets)
Component - Drawer
Component - Dropdown
Component - Dropdown-item
Component - Feedback
Component - FileInputArea
Component - FileInputArea item
Component - FieldGroup.item
Component - FieldGroup (Basic input + item)
Component - FieldGroup (Basic input + select)
Component - FieldGroup (Select + item)
Component - Glass-effect
Component - Icon (H1)
Component - Icon (H2)
Component - Icon (H3)
Component - Icon (H4)
Component - Icon (H5)
Component - Icon (Large)
Component - Icon (Medium)
Component - Icon (Small)
Component - Input/Basic input
Component - Label
Component - Link/bf-title-link
Component - Link/bf-neutral-link
Component - Link/bf-link
Component - Link/bf-link + bfc-base (neutral color)
Component - List/Basic-list-item
Component - List/TOC-list-item
Component - Menu
Component - Message/Expandable message
Component - Message/Basic message
Component - Message
Component - Nav/TopBar - Search
Component - Nav/TopBar - Item
Component - Nav - TopBar
Component - Nav - Sidebar
Component - Nav - Sidebar item (grouped)
Component - Nav - Sidebar item (single)
Component - Nav - Sidebar item (grouped - dropout)
Component - Nav - Sidebar item (sub item)
Component - Nav/Legend - Markings (horizontal)
Component - Modal
Component - Modal/Image
Component - Pagination
Component - ProgressBar
Component - Radio
Component - Radio-button
Component - RadioCard
Component - Section
Component - Section-header
Component - Scrollbar
Component - Select
Component - Select/Multi-select
Component - Skeleton
Component - Stepbar
Component - Spinner
Component - Sticky
Component - Switch
Component - Switch-button
Component - SwitchCard
Component - Table (variable)
Component - Tabs (with content)
Component - Tabs (bar only)
Component - Tag
Component - TextArea
Component - Tooltip
BIFROST_VAR_LIST_EOF

killall cfprefsd 2>/dev/null || true
echo "Removed: $count. Commented out/skipped: $skipped. Not found: $fail."
echo "Restart Figma so System Settings shows the correct state."
